export const APPLOGIN_NAME_THUNK = "APPLOGIN_NAME_THUNK";
export const APPLOGIN_NAME_SAGA = "APPLOGIN_NAME_SAGA";
export const APPLOGIN_PASSWORD_THUNK = "APPLOGIN_PASSWORD_THUNK";
export const APPLOGIN_PASSWORD_SAGA = "APPLOGIN_PASSWORD_SAGA";
export const APPLOGIN_BUTTON_THUNK = "APPLOGIN_BUTTON_THUNK";
export const APPLOGIN_SAGA = "APPLOGIN_SAGA";
export const APPLOGIN_BUTTON_SAGA = "APPLOGIN_BUTTON_SAGA";
export const APPLOGIN_BUTTON_TO_SAGA = "APPLOGIN_BUTTON_TO_SAGA";